### ISSUE TITLE
Cannot load/detect this package

### ISSUE THREAD

**Issue by Balroth** [consulo/UnityEditorConsuloPlugin#23]
I formated my pc, and have used Consulo in the past and ended up working perfectly https://github.com/consulo/consulo-unity3d/issues/178

So, I did this step by step more or less https://github.com/consulo/consulo-unity3d/wiki/1.-Setup-and-Usage
I deleted the previous .consulo folder, and the installation was smooth.

However! The plugin installation always goes wrong

I'm on Windows 7, Unity 2018.1.1f1
![14](https://user-images.githubusercontent.com/25630803/101701311-82f88400-3a33-11eb-9fe3-16b7214a7443.PNG)
![15](https://user-images.githubusercontent.com/25630803/101701316-85f37480-3a33-11eb-8db7-78da293e6f7b.PNG)

The manifest.json file:
![14](https://user-images.githubusercontent.com/25630803/101701336-91df3680-3a33-11eb-8080-8e0586014c99.PNG)

As for the plugin, I literally pressed the "Install Plugin/Manifest" or whatever Consulo pops up when it doesn't detect the plugin, and yeah this always happens. Is there a way to install it manually? Because I honestly do not even know how to download it since https://upm.consulo.io/#browse/browse/assets:unity is unbrowserable

**Comment by Balroth** [comment]
Solution I tried, to give more info:

1. Delete manifest.json file (I don't have any packages needed for my project anyway)
2. Consulo gives me the popup
![14](https://user-images.githubusercontent.com/25630803/101702038-f18a1180-3a34-11eb-9de4-fbf457f595f1.PNG)
3. Click install via manifest
4. Unity loads or whatever, then this happens in the console
![15](https://user-images.githubusercontent.com/25630803/101702069-04044b00-3a35-11eb-8afb-7a91efc30260.PNG)

**Comment by VISTALL** [comment]
Hello. There I problem of your old Unity version. I can't say when Unity supports custom repository before 2019.

 Can you try change it to git url?

> https://github.com/consulo/UnityEditorConsuloPlugin#for-advanced-users

**Comment by Balroth** [comment]
I kinda tried the above, if you mean changing the `https` to `http`

If you mean this 
`"dependencies": {
    "com.consulo.ide": "https://github.com/consulo/UnityEditorConsuloPlugin.git"
  }`

^Do you mean I should try replacing `"com.consulo.ide": "2.4.0"` with `"com.consulo.ide": "https://github.com/consulo/UnityEditorConsuloPlugin.git"`?

**Comment by VISTALL** [comment]
yeah

**Comment by Balroth** [comment]
The steps I did:
1. Delete the manifest.json (since it will happen again)
2. Open up Consulo and Open/Import the project
3. Detects no plugin, popup of plugin happens
4. Install via Manifest
5. Done
6. Tweak the text file as mentioned
7. Open up the Unity project
8. Get Error
![14](https://user-images.githubusercontent.com/25630803/101821512-e7bbe900-3adc-11eb-8192-36a40b1855c7.PNG)

Any tips/suggestions? Is there a way to download the plugin manually and put it on its proper folder?

**Comment by VISTALL** [comment]
Looks like you Unity not support custom packages. In this case need only download sources, and put it to project (in Assets/Plugins/Consulo for example)

Sorry, it cannot be fixed

**Comment by Balroth** [comment]
> Sorry, it cannot be fixed

But you also kinda said it can? xD

> In this case need only download sources, and put it to project (in Assets/Plugins/Consulo for example)

So, what do I download? Do you have a link?

**Comment by VISTALL** [comment]
Click **Download Zip**

![image](https://user-images.githubusercontent.com/542934/101824281-0baf1700-3b3d-11eb-8e59-628af7833e15.png)

> But you also kinda said it can? (quote below)

It's not fix - it's a compromise. Unity package system is ideal solution of get right version of plugin. Without it - need by hand update files, if you want new version.

**Comment by Balroth** [comment]
As long as it works, I don't care about new version xD

![14](https://user-images.githubusercontent.com/25630803/101829857-84d04f00-3ae8-11eb-8cf9-e9ffd0e00a6e.PNG)
![15](https://user-images.githubusercontent.com/25630803/101829870-8863d600-3ae8-11eb-97d5-430ea9bd4d06.PNG)
![16](https://user-images.githubusercontent.com/25630803/101829874-8ac63000-3ae8-11eb-8273-131e74a4a580.PNG)
![17](https://user-images.githubusercontent.com/25630803/101829877-8d288a00-3ae8-11eb-83a6-a658c475b668.PNG)
I went to change/edit
![18](https://user-images.githubusercontent.com/25630803/101829908-9ca7d300-3ae8-11eb-83e3-e32aeb349aff.PNG)
![19](https://user-images.githubusercontent.com/25630803/101830002-bcd79200-3ae8-11eb-82ab-c84fbc373d70.PNG)
![20](https://user-images.githubusercontent.com/25630803/101830008-bea15580-3ae8-11eb-94b5-a0421434f6b4.PNG)

I guess gg? Can old plugin versions work with current Consulo?
Since Consulo itself works nicely with Unity, all I want is to double click a .cs unity script and open it in Consulo pretty much lel

If there is no solution at all, that's alright, it's not too much a productivity kill, though I have to ask, how do I find a file under a subfolder in Consulo?

For example, I want to open a script in Unity, so instead of manually searching for it in Consulo, I just hotkey and type it (all scripts are under the Scripts folder in my project structure)
![21](https://user-images.githubusercontent.com/25630803/101830245-12ac3a00-3ae9-11eb-9894-d66e6bf97e4f.PNG)

**Comment by Balroth** [comment]
> Oh. CocurrentQueue - it's .NET 4.0 feature =/

Do not bother, users with less than .NET 4.0 are so low, not worth a refactoring for sure

> Old plugin less stable, and have not all implemented features which was added in new version.

I remember some crashes hahahaha, but there is no need now, as the hotkeys you provided me with, do exactly the same job as I wanted the plugin for! :grin:

Anyhow, thank you for your quick responses, and for solving this issue for me so fast, without even needing the plugin! :+1:

**Comment by VISTALL** [comment]
OK

**Comment by juanitogan** [comment]
I know this is closed but... just adding a note that I got this working in Unity 2017.4 with Consulo 2021.11.

Unity 2017 (starting with 2017.2, I think) has the Package Manager API but not the UI.  It has a `manifest.json` in the **UnityPackageManager** folder instead of in **Packages** (and 2017 ignores the `manifest.json` Consulo put here).  I tried moving the manifest setting to the 2017 location, but this early Package Manager version does not support this format:
```
    "com.consulo.ide": "https://github.com/consulo/UnityEditorConsuloPlugin.git#2.6.0"
```

According to the error message ([seen in an earlier comment above](https://github.com/consulo/UnityEditorConsuloPlugin/issues/23#issuecomment-742752821)) it wants this format and only this format:
```
    "com.consulo.ide": "2.4.0"
```

But, that only works with the http://upm.consulo.io/ server... which appears to be dead.

Thus, my only option seems to be to download the code manually instead.  But, because my Unity 2017 project still uses .NET 3.5, the latest code won't work, so I went looking for the older plugin code.  I found it in the **unityAssetStore** branch, here:

![image](https://user-images.githubusercontent.com/2923222/145143038-3f0d2f1f-3d93-4607-92e2-f0e5baa6ac2a.png)

----

I copied the **Assets\Scripts\Editor\Plugins\Consulo** folder from the downloaded zip into my project under **Assets\Editor\Plugins** and, voila, it works!  I can now click on files and error messages in Unity to open them up in Consulo.  (Note: I tried the old `UnityEditorConsuloPlugin2017.2.dll` file first and it did not work.)  Perhaps not ideal without whatever the later features are, but better than not having it... and better than Visual Studio.
